packages:
  - apps/*
  - packages/*

overrides:
  better-auth@<1.4.2: '>=1.4.2'
  better-auth@>=1.3.34 <1.4.0: '>=1.4.0'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  esbuild@<=0.24.2: '>=0.25.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  next@>=16.0.0-canary.0 <16.0.7: '>=16.0.7'
